##指定不同环境的配置文件
#spring:
#  profiles:
#    active: dev
#family:
#  family-name: "happy family"
#  father:
#    name: tom
##    age: ${random.int(50)}
#    age: 24
#    email: aaa@qq.com
#  mother:
#    alias:
#      - rose
#      - alice
#  child:
#    name: jack
#    age: 6
#    friends:
#      - hobby: football
#        gender: male
#      - hobby: sing
#        gender: female
server:
  port: 8888