primarydb:
  uniqueResourceName: primary
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: root
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual #用于检测数据库HikariCP连接是否存活。

secondarydb:
  uniqueResourceName: secondary
  xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
  xaProperties:
    url: jdbc:mysql://120.26.0.159:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    user: root
    password: root
  exclusiveConnectionMode: true
  minPoolSize: 3
  maxPoolSize: 10
  testQuery: SELECT 1 from dual

#spring:
#    datasource:
#    primary:
#      jdbc-url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    secondary:
#      jdbc-url: jdbc:mysql://120.26.0.159:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
server:
  port: 9090
#      driver-class-name: com.mysql.cj.jdbc.Driver