spring:
  freemarker:
    cache: false  #缓存配置 开发阶段应该配置为false,因为经常会改动
    suffix: .ftl #模板文件后缀名
    charset: UTF-8 #文件编码
    template-loader-path: classpath:/templates/

  thymeleaf:
    cache: false
    check-template-location: true    #检查模板是否存在
    enabled: true #是否启用
    encoding: UTF-8 #模板编码
    excluded-view-names: #应该从解析中排除的视图名称列表(用逗号分开)
    mode: HTML5 #模板模式
    prefix: classpath:/templates/ #模板存放路径
    suffix: .html #模板后缀